let tbody = document.getElementById("studentdata");
const array = [
    {
        sr_no : 1,
        name: "Denisha",
        age: 18,
        contact : "1234567890",
        enail : "denisha@j.com",  
    },
    {
        sr_no : 2,
        name: "Monika",
        age: 18,
        contact : "1234567890",
        enail : "monu@j.com",  
    },
    {
        sr_no : 3,
        name: "Divya",
        age: 18,
        contact : "1234567890",
        enail : "dayu@j.com",  
    },
    {
        sr_no : 4,
        name: "Aishwarya",
        age: 18,
        contact : "1234567890",
        enail : "ashu@j.com",  
    },
    {
        sr_no : 5,
        name: "Sushmita",
        age: 18,
        contact : "1234567890",
        enail : "sushmita@j.com",  
    },
    {
        sr_no : 6,
        name: "soni",
        age: 18,
        contact : "1234567890",
        enail : "soni@j.com",  
    },
    {
        sr_no : 7,
        name: "pintu",
        age: 18,
        contact : "1234567890",
        enail : "pintu@j.com",  
    },
    {
        sr_no : 8,
        name: "veer",
        age: 18,
        contact : "1234567890",
        enail : "veer@j.com",  
    },
    {
        sr_no : 9,
        name: "sonalika",
        age: 18,
        contact : "1234567890",
        enail : "sonuj.com",  
    },
    {
        sr_no : 10,
        name: "ravi",
        age: 18,
        contact : "1234567890",
        enail : "ravi@j.com",  
    },
    {
        sr_no : 11,
        name: "keval",
        age: 18,
        contact : "1234567890",
        enail : "keval@j.com",  
    },
    {
        sr_no : 12,
        name: "kavya",
        age: 18,
        contact : "1234567890",
        enail : "kavya@j.com",  
    },
    {
        sr_no : 13,
        name: "pari",
        age: 18,
        contact : "1234567890",
        enail : "pari@j.com",  
    },
    {
        sr_no : 14,
        name: "riddhi",
        age: 18,
        contact : "1234567890",
        enail : "riddhi@j.com",  
    },
    {
        sr_no : 15,
        name: "montu",
        age: 18,
        contact : "1234567890",
        enail : "montu@j.com",  
    },
    {
        sr_no : 16,
        name: "tulsi",
        age: 18,
        contact : "1234567890",
        enail : "tulsi@j.com",  
    },
    {
        sr_no : 17,
        name: "pal",
        age: 18,
        contact : "1234567890",
        enail : "pal@j.com",  
    },
    {
        sr_no : 18,
        name: "yashvi",
        age: 18,
        contact : "1234567890",
        enail : "yashvi@j.com",  
    },
    {
        sr_no : 19,
        name: "prathna",
        age: 18,
        contact : "1234567890",
        enail : "prathna@j.com",  
    },
    {
        sr_no : 20,
        name: "sakshi",
        age: 18,
        contact : "1234567890",
        enail : "sakshi@j.com",  
    },

] 
array.forEach((element) => {
    studentdata.innerHTML +=` <tr><td>${element.sr_no}</td><td>${element.name}</td><td>${element.age}</td><td>${element.contact}</td><td>${element.enail}</td></tr> `
});